name: backup_link
description: "A backup utility with symbolic link support"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.2
  file_picker: ^9.0.2
  flutter_progress_hud: ^2.0.2
  logger: ^2.5.0
  path: ^1.9.1
  win32: ^5.12.0
  crypto: ^3.0.3 # Adicionado pacote crypto

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  test: ^1.24.9
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/createSymlink.ps1
    - assets/lang/
