name: backup_link
description: "A backup utility with symbolic link support"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  file_picker: ^6.1.1
  flutter_progress_hud: ^2.0.2
  logger: ^2.0.2
  path: ^1.8.3
  provider: ^6.1.1
  win32: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  test: ^1.24.9
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/createSymlink.ps1
